import './globals.css'
import { Roboto } from 'next/font/google'
import Providers from '@/components/Providers'
import PageWrapper from '@/components/PageWrapper'

const BodyFont = Roboto({ subsets: ["latin"], weight: "700"})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html>
      <body className={`${BodyFont.className} uusm:min-w-[279px]`}>
        <Providers>
          <PageWrapper>
            {children}
          </PageWrapper>
        </Providers>
      </body>
    </html>
  )
}
