import './globals.css'
import { Roboto } from 'next/font/google'
import Providers from '@/components/Providers'
import Page from '@/components/Page'
import Navbar from '@/components/navbar/Component'

const BodyFont = Roboto({ subsets: ["latin"], weight: "700"})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({children}: { children: React.ReactNode }) {
  return (
    <html>
      <body className={`${BodyFont.className} uusm:min-w-[279px]`}>
        <Providers>
          <Navbar />
          <Page>
            {children}
          </Page>
        </Providers>
      </body>
    </html>
  )
}
